### PR TITLE
implement delete_contact_group()

### PR DESCRIPTION
**Pull request by luto**
This implements a method to delete created contact groups based on their ID.

https://www.statuscake.com/api/Contact%20Groups/Delete%20Contact%20Group.md

### CODE REVIEW

**Comment by trbs** [comment]
Thanks !

**Comment by luto** [comment]
yay! :) thanks for you quick merges.

**Comment by trbs** [comment]
No problem... 

You need a new release on PyPi as well ?

**Comment by luto** [comment]
Not yet, thanks!

**Pull request merged**
