### PR TITLE
[WIP] add a basic test setup

### PR DESCRIPTION
**Pull request by luto**
This PR aims to add a full test suite.

Currently implemented:
* get_node_locations()
* contact groups (all methods)

Are you fond of nosetests or would a switch to py.test be something you'd merge? The fixture system as well as things like `py.test -k` would come in handy.

Please let me know what you think :)

### CODE REVIEW

**Comment by trbs** [comment]
I nowadays use py.test for most other projects. Happy with either.

**Comment by luto** [comment]
Alright! :) this is py.test now. I'll continue working on it in a couple of days.

**Comment by luto** [comment]
We will not be using the service any longer. Sadly that also means that I won't put any more time into this library. You (or anyone else) are of course free to take and use the code already produced. sorry.

**Comment by trbs** [comment]
Thanks for all your help so far !

**Pull request closed without merging**
