### PR TITLE
Added SSL Endpoint for Update/Insert/Delete

### PR DESCRIPTION
**Pull request by Mudpuppy12**
This allows usage of StatusCake API for adding and remove API endpoints

### CODE REVIEW

**Comment by trbs** [comment]
Thanks for the PR ! Could you please fix travis errors ?

**Comment by Mudpuppy12** [comment]
Flake8 still hates me. I'll fix it up a bit later today.

**Comment by trbs** [comment]
Sorry for the strict style checking, but in the end it makes maintenance a lot easier.

**Comment by Mudpuppy12** [comment]
It's all good. It's my fault for being lazy.

**Comment by trbs** [comment]
Thanks !

**Pull request merged**
